services:
  db:
    command:
      - postgres
      - -c
      - fsync=on
      - -c
      - synchronous_commit=on
      - -c
      - max_connections=100
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - pg_stat_statements.track=all
      - -c
      - pg_stat_statements.track_planning=off
